"""IBM i qualification DML and source oracle via the capture image's JVM.

Only SQL generated by the deterministic qualification scenario is accepted.
The source password is read from a private file and sent to the short-lived
Java process on stdin; it never enters Docker arguments or the environment.
This driver is for a dedicated synthetic table, never an application table.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import os
from pathlib import Path
import re
import stat
import subprocess
from typing import Any, Callable, Sequence

from .adapters import SourceResult
from .config import RunConfig
from .generator import DML_STEP_NAMES, LABEL, freshness_markers, step_plan
from .schema import update_sql


_IMAGE_DIGEST = re.compile(r"(?:\S+@)?sha256:[0-9a-f]{64}\Z")
_SOURCE_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]{0,127}\Z")
_RECEIVER = re.compile(r"[A-Za-z0-9_$#@]{1,128}\Z")
_HOST = re.compile(r"[A-Za-z0-9][A-Za-z0-9.-]{0,252}\Z")
_USER = re.compile(r"[A-Za-z0-9_$#@]{1,128}\Z")
_KEYCHAIN_SERVICE = re.compile(r"[A-Za-z0-9][A-Za-z0-9/_-]{0,127}\Z")
_JAVA_CLASS = "io.quadringent.as400.QualificationSourceDriver"
_JAVA_CLASSPATH = "/app/probe.jar:/app/lib/*"


@dataclass(frozen=True)
class _Credential:
    host: str
    user: str
    password: str = field(repr=False)


def _load_credential(path_text: str, *, configured_host: str | None,
                     configured_user: str | None) -> _Credential:
    if path_text.startswith("keychain:"):
        service = path_text.removeprefix("keychain:")
        if _KEYCHAIN_SERVICE.fullmatch(service) is None:
            raise ValueError("source keychain service is invalid")
        if configured_host is None or configured_user is None:
            raise ValueError("source host and user are required with keychain")
        if _HOST.fullmatch(configured_host) is None or _USER.fullmatch(configured_user) is None:
            raise ValueError("source host or user is invalid")
        try:
            completed = subprocess.run(
                ["security", "find-generic-password", "-s", service, "-w"],
                capture_output=True, text=True, check=False, timeout=10,
            )
        except (OSError, subprocess.TimeoutExpired):
            raise ValueError("source keychain item is unavailable") from None
        password = completed.stdout.removesuffix("\n")
        if completed.returncode != 0 or not password or len(password) > 8192 or "\n" in password or "\r" in password:
            raise ValueError("source keychain item is unavailable")
        return _Credential(configured_host, configured_user, password)
    path = Path(path_text)
    try:
        if not hasattr(os, "O_NOFOLLOW"):
            raise ValueError("source secret requires a no-follow file open")
        descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
        with os.fdopen(descriptor, "r", encoding="utf-8") as handle:
            metadata = os.fstat(handle.fileno())
            if not stat.S_ISREG(metadata.st_mode) or metadata.st_uid != os.getuid():
                raise ValueError("source secret must be an owned regular file")
            if stat.S_IMODE(metadata.st_mode) & 0o077:
                raise ValueError("source secret file permissions must exclude group and others")
            if metadata.st_size > 16 * 1024:
                raise ValueError("source secret file exceeds size budget")
            payload = json.loads(handle.read(16 * 1024 + 1))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError("source secret file is unreadable or invalid") from error
    if not isinstance(payload, dict):
        raise ValueError("source secret file must contain an object")
    host = payload.get("host")
    user = payload.get("user")
    password = payload.get("password")
    if not isinstance(host, str) or _HOST.fullmatch(host) is None:
        raise ValueError("source host is invalid")
    if not isinstance(user, str) or _USER.fullmatch(user) is None:
        raise ValueError("source user is invalid")
    if not isinstance(password, str) or not password or "\n" in password or "\r" in password:
        raise ValueError("source password cannot use the stdin line protocol")
    if ((configured_host is not None and configured_host != host)
            or (configured_user is not None and configured_user != user)):
        raise ValueError("source host or user does not match secret file")
    return _Credential(host, user, password)


class DockerIbmiSourceDriver:
    """``SourceDriver`` backed by the product's pinned capture image."""

    def __init__(
        self,
        config: RunConfig,
        *,
        runner: Callable[..., Any] = subprocess.run,
    ) -> None:
        if config.source.driver != "ibmi_java":
            raise ValueError("source driver must be ibmi_java")
        if _IMAGE_DIGEST.fullmatch(config.capture.image) is None:
            raise ValueError("capture image must be pinned by sha256 digest")
        library, table = config.table.qualified_name.split(".")
        if library.upper() not in {name.upper() for name in config.source.library_whitelist}:
            raise ValueError("source table library is outside the allowlist")
        if any(
            _SOURCE_NAME.fullmatch(value) is None
            for value in (library, table, config.source.journal_library, config.source.journal_name,
                          config.table.primary_key, *config.table.column_names)
        ):
            raise ValueError("source identifier is invalid")
        self.config = config
        self._runner = runner
        self._credential = _load_credential(
            config.source.connection_secret_file,
            configured_host=config.source.host, configured_user=config.source.user,
        )
        self._library = library
        self._table = table
        self._allowed_sql: frozenset[str] | None = None

    def execute(self, statements: Sequence[str]) -> SourceResult:
        if not self.config.source.allow_dml:
            return SourceResult(exit_code=5)
        if self._allowed_sql is None:
            generated = {
                statement
                for step in DML_STEP_NAMES
                for statement in step_plan(step, self.config.table).statements
            }
            if "freshness" in self.config.steps:
                generated.update(
                    update_sql(self.config.table, 1, {LABEL: marker})
                    for marker in freshness_markers(self.config.run_id)
                )
            self._allowed_sql = frozenset(generated)
        if not statements or any(statement not in self._allowed_sql for statement in statements):
            raise ValueError("only generated qualification DML is allowed")
        return self._run("exec", statements)

    def tail(self) -> SourceResult:
        return self._run("tail")

    def inspect(self) -> SourceResult:
        """Relit sans mutation le journal attaché à la table configurée."""
        return self._run("inspect")

    def dump(self) -> SourceResult:
        return self._run("dump")

    def row_positions(self, starting: tuple[str, int]) -> SourceResult:
        receiver, sequence = starting
        if _RECEIVER.fullmatch(receiver) is None or isinstance(sequence, bool) or not isinstance(sequence, int) or sequence < 0:
            raise ValueError("source receiver position is invalid")
        return self._run("rowpos", extra=(receiver, str(sequence)))

    def rotate(self) -> SourceResult:
        if not self.config.source.allow_rotation:
            return SourceResult(exit_code=5)
        return self._run("rotate")

    def _run(self, mode: str, statements: Sequence[str] = (), *, extra: tuple[str, ...] = ()) -> SourceResult:
        command = [
            "docker", "run", "--rm", "--interactive", "--read-only",
            "--tmpfs", "/tmp:rw,nosuid,size=16m",
            "--pids-limit", "128", "--memory", "512m", "--cpus", "1",
            "--security-opt", "no-new-privileges", "--cap-drop", "ALL",
            "--entrypoint", "java", self.config.capture.image,
            "-cp", _JAVA_CLASSPATH, _JAVA_CLASS, mode,
            self._library, self._table,
            self.config.source.journal_library, self.config.source.journal_name,
            self.config.table.primary_key, ",".join(self.config.table.column_names),
            *extra,
        ]
        credential = self._credential
        stdin = f"{credential.host}\n{credential.user}\n{credential.password}\n"
        if statements:
            stdin += "".join(statement + "\n" for statement in statements)
        try:
            completed = self._runner(
                command, input=stdin, text=True, capture_output=True,
                timeout=min(120, self.config.capture.max_seconds), check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            return SourceResult(exit_code=124)
        if completed.returncode != 0:
            return SourceResult(exit_code=int(completed.returncode))
        accepted = {
            "exec": ("SRC_EXEC_TOTAL=",),
            "tail": ("SRC_TAIL=", "SRC_TAIL_COUNT="),
            "inspect": ("SRC_JOURNAL=",),
            "dump": ("SRC_ROW=", "SRC_ROW_COUNT="),
            "rowpos": ("SRC_RECEIVER=", "SRC_ROWPOS=", "SRC_ROWPOS_COUNT="),
            "rotate": ("SRC_ROTATED=",),
        }[mode]
        checks = tuple(
            line for line in (completed.stdout or "").splitlines()
            if line.startswith(accepted)
        )
        if mode == "exec" and checks != (f"SRC_EXEC_TOTAL={len(statements)}",):
            return SourceResult(exit_code=6)
        if mode == "tail":
            rows = [line for line in checks if line.startswith("SRC_TAIL=")]
            counts = [line for line in checks if line.startswith("SRC_TAIL_COUNT=")]
            if not rows or counts != [f"SRC_TAIL_COUNT={len(rows)}"]:
                return SourceResult(exit_code=6)
        if mode == "inspect" and len(checks) != 1:
            return SourceResult(exit_code=6)
        if mode in {"dump", "rowpos"}:
            prefix = "SRC_ROW" if mode == "dump" else "SRC_ROWPOS"
            counts = [line for line in checks if line.startswith(prefix + "_COUNT=")]
            rows = [line for line in checks if line.startswith(prefix + "=")]
            if (len(counts) != 1 or counts[0] != f"{prefix}_COUNT={len(rows)}"
                    or (mode == "rowpos" and not any(line.startswith("SRC_RECEIVER=") for line in checks))):
                return SourceResult(exit_code=6)
        if mode == "rotate" and checks != ("SRC_ROTATED=true",):
            return SourceResult(exit_code=6)
        return SourceResult(exit_code=0, checks=checks)
